name = "kkerti-dev"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "temperature-db"
database_id = "local-db"

[vars]
NODE_ENV = "development"